# Generated by Django 4.2.5 on 2023-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('mileage', models.PositiveIntegerField()),
                ('no_of_owners', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
